# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [19.7]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node Packages
        run: npm install

      - name: Check Code Format
        run: npm run lint
      
      # // TODO: https://www.pluralsight.com/guides/how-to-test-react-components-in-typescript
      # - name: Test Code
      #   run: npm run test -- --watchAll=false

  release:
    name: Publish Release
    needs: [test]
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 19.7

      - name: Install Node Packages
        run: npm install --only=dev

      - name: Build Package
        run: |
          rm -rf lib
          npm run build
      
      - name: Setup Git
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
      
      - name: Sync Setup Dependencies
        run: |
          git add lib/*
          if ! git diff --staged --quiet; then
            git commit -m "push build files [skip ci]"
            git push
          fi

      - name: Publish Semantic Release
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npx semantic-release
